version: "3"

services:
    drone-api:
        image: jaquelaurenti/drone-api
        ports:
            - "3333:3333"
        restart: "always"
        networks:
            - drone-radar
    
    
    frontend:
        image: jaquelaurenti/drone-radar-front
        ports:
            - "3000:3000"
        restart: "always"
        environment:
            - FIAP:DroneAddress=http://drone-api:3333/api/
        networks:
            - drone-radar
        
networks: 
    drone-radar: